name: environment_BPSD

channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python >=3.11.0, <4.0.0
  - pip >=23.1.0, <24.0.0
  - numpy >=1.23.0, <1.24.0
  - scipy >=1.10.0, <2.0.0
  - matplotlib >=3.7.0, <4.0.0
  - jupyter >=1.0.0, <2.0.0
  - pandas >=1.5.0, <2.0.0
  - scikit-learn >=1.2.0, <2.0.0
  - ffmpeg >=4.2.0, <5.0.0
  - numba >=0.57.0, <1.0.0
  - nbconvert >=6.5.0, <7.0.0
  - pytorch::pytorch >=2.0.0, <3.0.0
  - pytorch::torchvision >=0.15.0, <1.0.0
  - pytorch::torchaudio >=2.0.0, <3.0.0
  - pytorch::pytorch-cuda >=11.8, <12.0
  - pip:
    - mir-eval >=0.7.0, <1.0.0
    - nbstripout >=0.6.0, <1.0.0
    - music21 >=5.7.0, <6.0.0
    - pretty_midi >=0.2.0, <1.0.0
    - librosa >=0.9.0, <0.10.0
    - pysoundfile >=0.9.0, <1.0.0
    - libfmp
